sudo: required
dist: focal
services:
  - docker

before_install:
  - docker build -t lxdagr8/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lxdagr8/docker-react npm test

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: "frontend"
  env: "Frontend-env"
  bucket-name: "elasticbeanstalk-us-east-2-878302214899"
  bucket-path: "frontend"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"